# docker-compose.dev.yml
version: '3.8'

services:
  mongodb-dev:
    image: mongo:latest
    container_name: erikets-blog-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: erikets-blog-mongodb