# docker-compose.prod.yml
version: '3.8'

services:
  # NestJS Application Service
  nestjs-app:
    build:
    container_name: my-nestjs-app-prod
    ports:
      - "3000:3000"
    restart: always
    environment:
      DATABASE_URL: ${MONGO_DATABASE_URL}
    depends_on:
      - mongodb-prod

  # MongoDB Database Service
  mongodb-prod:
    image: mongo:7.0 
    container_name: erikets-blog-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb_prod_data:/data/db

# Define the named volume managed by Docker
volumes:
  mongodb_prod_data: